name = "hono-react-ssr-shadcn-ui"
pages_build_output_dir = "./dist"
compatibility_date = "2024-04-22"

[vars]
BLOG_USERNAME="admin"
BLOG_PASSWORD="123456"

[[kv_namespaces]]
binding = "CFBLOG"
id = "345a36d4412c429b9887eecd297a8ee7"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
