name = "hono-react-ssr-shadcn-ui"
pages_build_output_dir = "./dist"
compatibility_date = "2024-04-22"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "blog"
id = "8617f8968998499bb3db425063f8f01d"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"